import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'

import { AIResearchPanel } from './AIResearchPanel'

describe('AIResearchPanel', () => {
  it('renders the advanced research workspace with the privacy-first entry flow', () => {
    const html = renderToStaticMarkup(<AIResearchPanel />)

    expect(html).toContain('Research any place on Earth')
    expect(html).toContain('Research area')
    expect(html).toContain('Research archive')
    expect(html).toContain('Approved AI tests')
    expect(html).toContain('Stare moduły')
    expect(html).toContain('wszystkie zachowane zakładki i laboratoria')
    expect(html).toContain('Prosty')
    expect(html).toContain('Zaawansowany')
    expect(html).toContain('obrazy HQ · pliki · modele · flagi · DEM · profile · raporty')
    expect(html).toContain('Wpisz miejsce. Resztę przygotuje system.')
    expect(html).toContain('Zapytaj asystenta')
    expect(html).toContain('PYTANIE PRYWATNE · TYLKO SESJA')
    expect(html).toContain('Odpowiedź pojawia się bezpośrednio tutaj')
    expect(html).toContain('Wyślij prywatnie')
    expect(html).toContain('1990–dziś')
    expect(html).toContain('ZIEMIA 3D · KAFELKOWA MAPA REFERENCYJNA')
    expect(html).toContain('high-resolution basemap')
    expect(html).not.toContain('YOU / RESEARCHER')
    expect(html).not.toContain('Research account · Sign in with ChatGPT')
    expect(html).not.toContain('Continue with ChatGPT — not configured')
    expect(html).not.toContain('OPENAI_API_KEY')
  })

  it('renders contest quick access while keeping the advanced laboratory reachable', () => {
    const html = renderToStaticMarkup(<AIResearchPanel simpleOnly />)

    expect(html).toContain('SIMPLE + ADVANCED')
    expect(html).toContain('Research any place on Earth')
    expect(html).toContain('BUILD FOR GOOD · QUICK ACCESS')
    expect(html).toContain('Tests 1–16')
    expect(html).toContain('TEST 001')
    expect(html).toContain('TEST 016')
    expect(html).toContain('Eclipse Live 2026')
    expect(html).toContain('Arctic 90°N Research Station')
    expect(html).toContain('Sahara Research Station')
    expect(html).toContain('Ocean Research Station')
    expect(html).toContain('Earth–Space 512 Station')
    expect(html).toContain('Results Dashboard')
    expect(html).toContain('Sentinel-1 Map')
    expect(html).toContain('Analysis Report')
    expect(html).toContain('Observation Timeline')
    expect(html).toContain('JSON Data')
    expect(html).toContain('TP-26 Constellation')
    expect(html).toContain('Multi-angle Observation')
    expect(html).toContain('Investigation Support')
    expect(html).toContain('Forum')
    expect(html).toContain('L4 Training #1')
    expect(html).toContain('L4 Training #2 · Site Corpus')
    expect(html).toContain('L4 Training #3 · Streaming NASA GIBS')
    expect(html).toContain('experiment-001/')
    expect(html).toContain('flood-map/')
    expect(html).toContain('reports/copernicus-analysis.html')
    expect(html).toContain('Wpisz miejsce. Resztę przygotuje system.')
    expect(html).toContain('Zapytaj asystenta')
    expect(html).toContain('Zaawansowany')
    expect(html).toContain('stary pełny panel')
    expect(html).not.toContain('Approved AI tests')
    expect(html).not.toContain('Research archive')
  })
})
