export type PublicResearchTest = {
  testId: string
  label: string
  title: string
  category: string
  temporalScope: string
  publicPath: string
  aiCaseId?: string
  archiveStatus: 'published'
}

export const PUBLIC_RESEARCH_TESTS: PublicResearchTest[] = [
  {
    testId: '001',
    label: 'TEST 001',
    title: 'Forest pond near Lake Kuchnia — satellite-change record and long-term field observations',
    category: 'water / hydrology / terrain',
    temporalScope: '1990–2026 · spring + autumn',
    publicPath: 'experiment-001/',
    aiCaseId: 'test-001-forest-pond-kuchnia',
    archiveStatus: 'published',
  },
  {
    testId: '002',
    label: 'TEST 002',
    title: 'Surface-water change — multi-year comparison',
    category: 'water / surface change',
    temporalScope: '1990–2026',
    publicPath: 'experiment-002/',
    archiveStatus: 'published',
  },
  {
    testId: '003',
    label: 'TEST 003',
    title: 'Lake Nogat — water-change monitoring',
    category: 'water / lakes',
    temporalScope: '1990–2026',
    publicPath: 'experiment-003/',
    archiveStatus: 'published',
  },
  {
    testId: '004',
    label: 'TEST 004',
    title: 'Kacze + Głęboczek — reservoir comparison',
    category: 'water / lakes',
    temporalScope: '1990–2026',
    publicPath: 'experiment-004/',
    archiveStatus: 'published',
  },
  {
    testId: '005',
    label: 'TEST 005',
    title: 'Lake Tarpno — satellite monitoring',
    category: 'water / lakes',
    temporalScope: 'multi-year satellite record',
    publicPath: 'experiment-005/',
    archiveStatus: 'published',
  },
  {
    testId: '006',
    label: 'TEST 006',
    title: 'Lake Wieczno — control test for water change',
    category: 'water / control',
    temporalScope: 'multi-year satellite record',
    publicPath: 'experiment-006/',
    archiveStatus: 'published',
  },
  {
    testId: '007',
    label: 'TEST 007',
    title: 'Karaś / Iława — local water monitoring',
    category: 'water / local monitoring',
    temporalScope: 'multi-year satellite record',
    publicPath: 'experiment-007/',
    archiveStatus: 'published',
  },
  {
    testId: '008',
    label: 'TEST 008',
    title: 'Lake Stelchno — change monitoring',
    category: 'water / lakes',
    temporalScope: 'multi-year satellite record',
    publicPath: 'experiment-008/',
    archiveStatus: 'published',
  },
  {
    testId: '009',
    label: 'TEST 009',
    title: 'Lake Płowęż — change monitoring',
    category: 'water / lakes',
    temporalScope: 'multi-year satellite record',
    publicPath: 'experiment-009/',
    archiveStatus: 'published',
  },
  {
    testId: '010',
    label: 'TEST 010',
    title: 'Drwęca Valley — river, wetlands and surroundings',
    category: 'river / wetlands / hydrology',
    temporalScope: 'multi-year satellite record',
    publicPath: 'experiment-010/',
    archiveStatus: 'published',
  },
  {
    testId: '011',
    label: 'TEST 011',
    title: 'Iława–Zalewo — seasonal satellite evidence',
    category: 'water / regional monitoring',
    temporalScope: '1990–2026 · spring + autumn',
    publicPath: 'experiment-011/',
    aiCaseId: 'test-011-ilawa-zalewo',
    archiveStatus: 'published',
  },
  {
    testId: '012',
    label: 'TEST 012',
    title: 'Great Salt Lake — large-lake monitoring',
    category: 'water / lakes / USA',
    temporalScope: 'multi-year satellite record',
    publicPath: 'experiment-012/',
    archiveStatus: 'published',
  },
  {
    testId: '013',
    label: 'TEST 013',
    title: 'Cosmopolis / Grays Harbor — coast and estuary',
    category: 'coast / estuary / water',
    temporalScope: '1990–2026 · spring + autumn',
    publicPath: 'experiment-013/',
    aiCaseId: 'test-013-grays-harbor',
    archiveStatus: 'published',
  },
  {
    testId: '014',
    label: 'TEST 014',
    title: 'Vistula Gniew–Grudziądz — river and water-system monitoring',
    category: 'river / hydrology',
    temporalScope: '1990–2026 · spring + autumn',
    publicPath: 'experiment-014/',
    aiCaseId: 'vistula-test-014',
    archiveStatus: 'published',
  },
  {
    testId: '015',
    label: 'TEST 015',
    title: 'Himalayas / Tibetan Plateau — terrain, snow and water',
    category: 'terrain / snow / water',
    temporalScope: '1990–2026 · spring + autumn',
    publicPath: 'experiment-015/',
    aiCaseId: 'test-015-himalaya-tibet',
    archiveStatus: 'published',
  },
  {
    testId: '016',
    label: 'TEST 016',
    title: 'Water + terrain + AI — multi-source research direction',
    category: 'AI / terrain / hydrology',
    temporalScope: 'multi-source research',
    publicPath: 'experiment-016/',
    archiveStatus: 'published',
  },
]

export const PUBLIC_RESEARCH_CATEGORIES = [
  'all',
  ...Array.from(new Set(PUBLIC_RESEARCH_TESTS.map(item => item.category))).sort(),
]
